In [13]:
import pandas as pd

In [14]:
path = "C:/Users/gianl/Desktop/Gi/Supsi/MartaLauraGiada/Marta/MBFC_WebScraping/"

In [18]:
merged = pd.read_csv(path + "pro_science.csv")
# conspiracy = pd.read_csv(path + "conspiracy.csv")
# conspiracy

In [34]:
merged = pd.concat([conspiracy, fake], axis=0)
merged = merged.drop_duplicates()
merged.reset_index(drop=True, inplace=True)
merged

                              url credibility description
0       https://freeworldnews.tv/         low  conspiracy
1    https://21stcenturywire.com/         low  conspiracy
2            https://79days.news/         low  conspiracy
3            https://369news.net/         low  conspiracy
4           https://911truth.org/         low  conspiracy
..                            ...         ...         ...
933          https://www.yc.news/         low   fake_news
934         https://yournews.com/         low   fake_news
935  https://yubasuttertimes.com/         low   fake_news
936           https://z3news.com/         low   fake_news
937          https://zenith.news/         low   fake_news

[938 rows x 3 columns]

In [19]:
urls = list(merged["url"])
lst = [i[:-1].split("//")[1] for i in urls]
final = []
for i in lst:
    if "www." in i:
        value = i.split("www.")[1]
    else:
        value = i
    final.append(value)
merged["url"] = final
merged

                              url credibility  description
0                 airspacemag.com        high  pro science
1   allianceforscience.cornell.ed        high  pro science
2                         aaas.or        high  pro science
3                      cancer.org        high  pro science
4                         agu.org        high  pro science
..                            ...         ...          ...
79                       unep.org        high  pro science
80                       ornl.gov        high  pro science
81                   vaxopedia.or        high  pro science
82             verywellfamily.com        high  pro science
83                      webmd.com        high  pro science

[84 rows x 3 columns]

In [20]:
merged.to_csv("C:/Users/gianl/Desktop/Gi/Supsi/MartaLauraGiada/Marta/MBFC_WebScraping/pro_science.csv",
             line_terminator="\n", encoding="utf-8", index=False)

In [21]:
low_ita = pd.read_excel("C:/Users/gianl/Desktop/Gi/Supsi/MartaLauraGiada/Laura/Files/Book_Gianluca.xlsx")
low_global = pd.read_csv("C:/Users/gianl/Desktop/Gi/Supsi/MartaLauraGiada/Marta/MBFC_WebScraping/conspiracy_fake.csv")
high_global = pd.read_csv("C:/Users/gianl/Desktop/Gi/Supsi/MartaLauraGiada/Marta/MBFC_WebScraping/pro_science.csv")

final = low_ita.append(low_global)
final = final.append(high_global)
final.drop_duplicates(inplace=True)
final.reset_index(drop=True, inplace=True)
final = final[["url", "credibility"]]
final

<ipython-input-21-93bc0b3fcb44>:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final = low_ita.append(low_global)
<ipython-input-21-93bc0b3fcb44>:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final = final.append(high_global)

                             url credibility
0             il-quotidiano.info         low
1     terrarealtime.blogspot.com         low
2             it.sputniknews.com         low
3                  laverita.info         low
4            liberoquotidiano.it         low
...                          ...         ...
1271                    unep.org        high
1272                    ornl.gov        high
1273                vaxopedia.or        high
1274          verywellfamily.com        high
1275                   webmd.com        high

[1276 rows x 2 columns]

In [24]:
final.to_csv("C:/Users/gianl/Desktop/Gi/Supsi/MartaLauraGiada/final_urls.csv", index=False, 
             line_terminator='\n', encoding="utf-8")